# Generated by Django 4.2 on 2023-05-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reactiontype_alter_reply_tweet_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='type',
        ),
    ]
