# Generated by Django 4.2 on 2023-05-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0006_alter_replyreaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyreaction',
            unique_together={('reply', 'profile')},
        ),
        migrations.RemoveField(
            model_name='replyreaction',
            name='tweet',
        ),
    ]
