# Generated by Django 4.2 on 2023-05-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_reaction_tweet_replyreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyreaction',
            name='tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.tweet'),
            preserve_default=False,
        ),
    ]
