# Generated by Django 4.2 on 2023-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0005_replyreaction_tweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyreaction',
            unique_together={('reply', 'profile', 'tweet')},
        ),
    ]
